apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: default
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "{{ .Values.minInstances }}"
        autoscaling.knative.dev/maxScale: "{{ .Values.maxInstances }}"
        run.googleapis.com/ingress: "{{ .Values.ingress }}"
        run.googleapis.com/execution-environment: "{{ .Values.executionEnvironment }}"
    spec:
      containers:
      - image: "{{ .Values.image }}"
        name: "{{ .Values.containerName }}"
        env:
          - name: PORT
            value: "{{ .Values.port }}"
        resources:
          limits:
            cpu: "{{ .Values.resources.cpu }}"
            memory: "{{ .Values.resources.memory }}"
