version: '3'

vars:
  SPRING_PROFILES_ACTIVE: development

tasks:
  build:
    desc: "Build the project with Gradle"
    cmds:
      - ./gradlew clean build

  docker-build:
    desc: "Build the Docker image for hello-world-api"
    deps:
      - build
    cmds:
      - cd app && docker build -t hello-world-api .

  docker-run:
    desc: "Run the Docker image with a specified Spring profile"
    cmds:
      - docker run --rm -e SPRING_PROFILES_ACTIVE={{.SPRING_PROFILES_ACTIVE}} -p 8080:8080 hello-world-api

  compose-up:
    desc: "Run docker-compose with a specified Spring profile"
    deps:
      - docker-build
    cmds:
      - SPRING_PROFILES_ACTIVE={{.SPRING_PROFILES_ACTIVE}} docker-compose -f app/docker-compose.yml up --build

  compose-down:
    desc: "Stop and remove docker-compose services"
    cmds:
      - docker-compose -f app/docker-compose.yml down

  run-curl-loop:
    cmds:
      - |
        while true; do  
          RANDOM_NUMBER=$((1 + RANDOM % 10000))
          curl -X GET http://hello-world-api:8080/hello \
            -H "X-Trace-Token: trace-12345" \
            -H "X-Correlation-Id: corr-67890" \
            -H "X-CUSTOM-HEADER: customValue-$RANDOM_NUMBER"; 
          sleep 3; 
        done
    silent: true
    desc: "Run a loop to repeatedly call the hello-world API with random headers."
