version: '3.8'

services:
  hello-world-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yml"]
    environment:
      - OTELCOL_USELOCALHOSTASDEFAULTHOST=false
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"  # OTLP gRPC endpoint
      - "13133:13133"  # Health check endpoint
      - "1888:1888"  # pprof extension
      - "55679:55679"  # zpages extension
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # Jaeger UI
      - "14250:14250"  # Jaeger gRPC endpoint (for Jaeger clients)
      - "4318:4318"    # Jaeger's OTLP HTTP endpoint

  api-caller:
    image: curlimages/curl:7.85.0
    depends_on:
      - hello-world-api
    entrypoint: >
      /bin/sh -c 'while true; do  
        curl -X GET http://hello-world-api:8080/hello \
        -H "X-Trace-Token: trace-12345" \
        -H "X-Correlation-Id: corr-67890" \
        -H "X-CUSTOM-HEADER: customValue-$((1 + RANDOM % 10000))"; 
        sleep 3; 
      done'
